/*
 * bl.c
 *
 *  Created on: Feb 17, 2026
 *      Author: mark
 *
 *  TODO:
 *  	Change command codes to custom
 *  	Change ACK / NACK codes to custom
 *  	CID command: read revision as well
 *  	Modify version command to work with string
 *  	DFU implementation
 *  	Flash erase returns the error code generated by the HAL erase function (0xFFFFFFFF) --> decode this at the host side!!
 *  	Implement to be able to write not just to flash but to SRAM as well
 */

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "bl.h"
#include "config.h"
#include "stm32f1xx_hal.h"
#include "log.h"

#define ACK_CODE			0xAA
#define NACK_CODE			0xDD

#define CMD_GET_VER			0x01U
#define CMD_GET_HELP		0x52U
#define CMD_GET_CID			0x53U
#define CMD_GET_RDP_STA		0x54U
#define CMD_JUMP_TO_ADDR 	0x55U
#define CMD_FLASH_ERASE		0x56U
#define CMD_MEM_W			0x57U
#define CMD_EN_R_W_PROT		0x58U
#define CMD_MEM_R			0x59U
#define CMD_GET_SECTOR_STA	0x5AU
#define CMD_OTP_R			0x5BU
#define CMD_DIS_R_W_PROT	0x5CU

#define SRAM_SIZE			(20U * 1024U)
#define SRAM_END			(SRAM_BASE + (SRAM_SIZE - 1U))

#define PAGE_NUM			128

typedef enum {
	BL_RESP_ACK,
	BL_RESP_NACK
} BL_RESP_te;

struct internal_state_s {
	UART_HandleTypeDef uart_handle;
	CRC_HandleTypeDef crc_handle;
	uint8_t rx_buf[CONFIG_BL_RX_BUF_SIZE];
	bool initialized;
	bool started;
};
static struct internal_state_s internal_state;

static const uint8_t supported_cmds[] = {
    CMD_GET_VER,
    CMD_GET_HELP,
    CMD_GET_CID,
    CMD_GET_RDP_STA,
    CMD_JUMP_TO_ADDR,
    CMD_FLASH_ERASE,
    CMD_MEM_W,
    CMD_EN_R_W_PROT,
    CMD_MEM_R,
    CMD_GET_SECTOR_STA,
    CMD_OTP_R,
    CMD_DIS_R_W_PROT
};

static int cmd_get_ver_handler(uint8_t *packet);
static int cmd_get_help_handler(uint8_t *packet);
static int cmd_get_cid_handler(uint8_t *packet);
static int cmd_get_rdp_sta_handler(uint8_t *packet);
static int cmd_jump_to_addr_handler(uint8_t *packet);
static int cmd_flash_erase_handler(uint8_t *packet);
static int cmd_mem_w_handler(uint8_t *packet);
static int cmd_mem_r_handler(uint8_t *packet);
static int cmd_en_r_w_prot_handler(uint8_t *packet);
static int cmd_dis_r_w_prot_handler(uint8_t *packet);
static int cmd_get_sector_sta_handler(uint8_t *packet);
static int cmd_otp_r_handler(uint8_t *packet);

static int send_resp(BL_RESP_te resp, uint8_t resp_len);

static int get_ver(char *ver_o, uint8_t buf_len);
static uint32_t get_crc(uint8_t *data, uint32_t data_len);

typedef enum {
	CRC_RES_OK,
	CRC_RES_FAIL
} CRC_RES_te;
static CRC_RES_te verify_crc(uint8_t *data, uint32_t data_len, uint32_t crc);

typedef enum {
	ADDR_RES_OK,
	ADDR_RES_FAIL
} ADDR_RES_te;
static ADDR_RES_te verify_addr(uint32_t addr, bool verify_t_bit);

typedef enum {
	SECT_RES_OK,
	SECT_RES_FAIL
}SECT_RES_te;
static SECT_RES_te verify_page(uint8_t start_page, uint8_t num_page);

int bl_init(BL_CONFIG_ts *bl_config) {
	if(internal_state.initialized) {
		return -1;
	}

	internal_state.uart_handle = bl_config->uart_handle;
	internal_state.crc_handle = bl_config->crc_handle;

	internal_state.initialized = true;

	return 0;
}

int bl_start(void) {
	if(!internal_state.initialized || internal_state.started) {
		return -1;
	}

	internal_state.started = true;

	return 0;
}

int bl_run(void) {
	if(!internal_state.started) {
		return -1;
	}

	// Receive length information
	HAL_UART_Receive(&internal_state.uart_handle, internal_state.rx_buf, 1, HAL_MAX_DELAY);
	// Receive packet
	HAL_UART_Receive(&internal_state.uart_handle, internal_state.rx_buf + 1, internal_state.rx_buf[0], HAL_MAX_DELAY);

	switch(internal_state.rx_buf[1]) {
	  	case CMD_GET_VER:
	  		cmd_get_ver_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_GET_HELP:
	  		cmd_get_help_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_GET_CID:
	  		cmd_get_cid_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_GET_RDP_STA:
	  		cmd_get_rdp_sta_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_JUMP_TO_ADDR:
	  		cmd_jump_to_addr_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_FLASH_ERASE:
	  		cmd_flash_erase_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_MEM_W:
	  		cmd_mem_w_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_MEM_R:
	  		cmd_mem_r_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_EN_R_W_PROT:
	  		cmd_en_r_w_prot_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_DIS_R_W_PROT:
	  		cmd_dis_r_w_prot_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_GET_SECTOR_STA:
	  		cmd_get_sector_sta_handler(internal_state.rx_buf);
	  		break;
	  	case CMD_OTP_R:
	  		cmd_otp_r_handler(internal_state.rx_buf);
	  		break;
	  	default:
	  		log_print("bootloader: invalid command\r\n");
	  		break;
	  }

	return 0;
}

/**
 * @brief Sends bootloader version information to the host.
 *
 * @param[in] packet The command received.
 * @return 0 if success, -1 if failed.
 */
static int cmd_get_ver_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 6) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);

	// If CRC is correct send ACK
	if(crc_check_res == CRC_RES_OK) {
		/*log_print("bootloader: CRC check success\r\n");
		log_print("bootloader: sending version information\r\n");

		send_resp(BL_RESP_ACK, 1);

		char version[8];
		get_ver(version, sizeof(version));
		//HAL_UART_Transmit(&internal_state.uart_handle, (uint8_t*)version, strlen(version), HAL_MAX_DELAY);			// <-- Correct !!
		uint8_t ver = 0x10;
		HAL_UART_Transmit(&internal_state.uart_handle, &ver, 1, HAL_MAX_DELAY);*/

		log_print("bootloader: CRC check success\r\n");
		log_print("bootloader: sending version information\r\n");

		uint8_t write_data[7];
		write_data[0] = 6;
		write_data[1] = ACK_CODE;
		write_data[2] = 0x10;

		uint32_t crc = get_crc(write_data, 3);

		for(uint32_t i = 0; i < 4; i++) {
			write_data[3 + i] = (crc >> (8 * i)) & 0xFF;
		}

		HAL_UART_Transmit(&internal_state.uart_handle, write_data, sizeof(write_data), HAL_MAX_DELAY);

	}
	// If CRC is incorrect send NACK
	else {
		log_print("bootloader: CRC check failed\r\n");

		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	return 0;
}

/**
 * @brief Sends available command list information to the host.
 *
 * @param[in] packet The command received.
 * @return 0 if success, -1 if failed.
 */
static int cmd_get_help_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 6) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);

	// If CRC is correct send ACK
	if(crc_check_res == CRC_RES_OK) {
		log_print("bootloader: CRC check success\r\n");
		log_print("bootloader: sending help information\r\n");
		send_resp(BL_RESP_ACK, sizeof(supported_cmds));

		HAL_UART_Transmit(&internal_state.uart_handle, supported_cmds, sizeof(supported_cmds), HAL_MAX_DELAY);
	}
	// If CRC is incorrect send NACK
	else {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	return 0;
}

/**
 * @brief Sends chip identification information to the host.
 *
 * @param[in] packet The command received.
 * @return 0 if success, -1 if failed.
 */
static int cmd_get_cid_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 6) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);

	// If CRC is correct send ACK
	if(crc_check_res == CRC_RES_OK) {
		log_print("bootloader: CRC check success\r\n");
		log_print("bootloader: sending CID information\r\n");

		uint16_t cid = (uint16_t)(DBGMCU->IDCODE & 0x0FFF);

		send_resp(BL_RESP_ACK, sizeof(cid));

		HAL_UART_Transmit(&internal_state.uart_handle, (uint8_t*)&cid, sizeof(cid), HAL_MAX_DELAY);
	}
	// If CRC is incorrect send NACK
	else {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	return 0;
}

/**
 * @brief Sends readout protection information to the host.
 *
 * @param[in] packet The command received.
 * @return 0 if success, -1 if failed.
 */
static int cmd_get_rdp_sta_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 6) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);

	// If CRC is correct send ACK
	if(crc_check_res == CRC_RES_OK) {
		log_print("bootloader: CRC check success\r\n");
		log_print("bootloader: sending RDP information\r\n");

		FLASH_OBProgramInitTypeDef ob_handle;
		HAL_FLASHEx_OBGetConfig(&ob_handle);
		uint8_t rdp_level = ob_handle.RDPLevel;

		send_resp(BL_RESP_ACK, sizeof(rdp_level));

		HAL_UART_Transmit(&internal_state.uart_handle, &rdp_level, sizeof(rdp_level), HAL_MAX_DELAY);
	}
	// If CRC is incorrect send NACK
	else {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	return 0;
}

static int cmd_jump_to_addr_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 10) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	// If CRC is incorrect send NACK
	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);
	if(crc_check_res != CRC_RES_OK) {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t addr;
	memcpy(&addr, &packet[packet_len - 8], sizeof(uint32_t));

	ADDR_RES_te res = verify_addr(addr, false);
	if(res != ADDR_RES_OK) {
		log_print("bootloader: invalid address\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	// If CRC is correct send ACK
	log_print("bootloader: CRC check success\r\n");
	log_print("bootloader: jumping to specified address\r\n");

	send_resp(BL_RESP_ACK, 1);

	void (*dest)(void);
	dest = (void*)(addr);			// dest = (void*)(addr + 1); If user doesn't specify T bit
	dest();

	return 0;
}

static int cmd_flash_erase_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 8) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	// If CRC is incorrect send NACK
	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);
	if(crc_check_res != CRC_RES_OK) {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}
	log_print("bootloader: CRC check success\r\n");

	send_resp(BL_RESP_ACK, 4);

	uint8_t start_page = packet[2];
	uint8_t num_page = packet[3];

	SECT_RES_te res = verify_page(start_page, num_page);
	if(res != SECT_RES_OK) {
		log_print("bootloader: invalid arguments");
		return -1;
	}

	FLASH_EraseInitTypeDef flash;

	// Mass erase
	if(start_page == 0xFF) {
		flash.TypeErase = FLASH_TYPEERASE_MASSERASE;
		flash.Banks = FLASH_BANK_1;
	}
	// Page erase
	else {
		flash.TypeErase = FLASH_TYPEERASE_PAGES;
		flash.PageAddress = (start_page * PAGESIZE) + FLASH_BASE;
		flash.NbPages = num_page;
	}

	uint32_t err;

	HAL_FLASH_Unlock();
	HAL_FLASHEx_Erase(&flash, &err);
	HAL_FLASH_Lock();

	HAL_UART_Transmit(&internal_state.uart_handle, (uint8_t*)&err, sizeof(err), HAL_MAX_DELAY);

	if(err != 0xFFFFFFFF) {
		// Erase was unsuccessful
		log_print("bootloader: erase failed\r\n");
		return -1;
	}

	return 0;
}

static int cmd_mem_w_handler(uint8_t *packet) {
	uint8_t packet_len = packet[0] + 1;

	if(packet_len < 12) {
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}

	uint32_t crc = 0;
	memcpy(&crc, &packet[packet_len - 4], sizeof(uint32_t));

	// If CRC is incorrect send NACK
	CRC_RES_te crc_check_res = verify_crc(packet, packet_len - 4, crc);
	if(crc_check_res != CRC_RES_OK) {
		log_print("bootloader: CRC check failed\r\n");
		send_resp(BL_RESP_NACK, 0);

		return -1;
	}
	log_print("bootloader: CRC check success\r\n");					// <== overwrites data in internal_state.rx_buf and causes corruption

	send_resp(BL_RESP_ACK, 1);

	uint32_t addr;
	memcpy(&addr, &packet[2], sizeof(uint32_t));

	ADDR_RES_te res = verify_addr(addr, false);
	if(res != ADDR_RES_OK) {
		log_print("bootloader: invalid address");
		return -1;
	}

	uint8_t payload_len = packet[6];
	uint8_t *payload = &packet[7];
	uint8_t err;

	HAL_FLASH_Unlock();

	for(uint8_t i = 0; i < payload_len; i += 2) {
		uint16_t data = *(uint16_t*)(payload + i);

		err = HAL_FLASH_Program(FLASH_TYPEPROGRAM_HALFWORD, addr + i, data);
	    if(err != HAL_OK) {
	    	HAL_FLASH_Lock();

	    	HAL_UART_Transmit(&internal_state.uart_handle, (uint8_t*)&err, sizeof(err), HAL_MAX_DELAY);

	    	return -1;
	    }
	}
	HAL_FLASH_Lock();

	HAL_UART_Transmit(&internal_state.uart_handle, (uint8_t*)&err, sizeof(err), HAL_MAX_DELAY);

	return 0;
}

static int cmd_mem_r_handler(uint8_t *packet) {
	return 0;
}

static int cmd_en_r_w_prot_handler(uint8_t *packet) {
	return 0;
}

static int cmd_dis_r_w_prot_handler(uint8_t *packet) {
	return 0;
}

static int cmd_get_sector_sta_handler(uint8_t *packet) {
	return 0;
}

static int cmd_otp_r_handler(uint8_t *packet) {
	return 0;
}

/**
 * @brief Sends a response to the host after a command has been received.
 * Sends either an ACK (1 byte) with length information (1 byte) of the following response.
 *
 * @param[in] resp The response to send.
 * @return 0 if success, -1 if failed.
 */
static int send_resp(BL_RESP_te resp, uint8_t resp_len) {
	if(resp == BL_RESP_ACK) {
		uint8_t resp_msg[2];

		resp_msg[0] = ACK_CODE;
		resp_msg[1] = resp_len;

		HAL_UART_Transmit(&internal_state.uart_handle, resp_msg, 2, HAL_MAX_DELAY);
	}
	else if(resp == BL_RESP_NACK) {
		uint8_t resp_msg = NACK_CODE;

		HAL_UART_Transmit(&internal_state.uart_handle, &resp_msg, 1, HAL_MAX_DELAY);
	}

	return 0;
}

/**
 * @brief Verifies the CRC of a data sequence.
 *
 * @param[in] data Pointer to the data sequence to verify.
 * @param[in] data_len Length of the data to verify.
 * @param[in] crc_expected The expected CRC value.
 * @return CRC_RES_te CRC_RES_OK, CRC_RES_FAIL
 */
static CRC_RES_te verify_crc(uint8_t *data, uint32_t len, uint32_t crc_host)
{
    __HAL_CRC_DR_RESET(&internal_state.crc_handle);

    uint32_t crc_calculated = 0;

    for (uint32_t i = 0; i < len; i++) {
        uint32_t current_data = data[i];
        crc_calculated = HAL_CRC_Accumulate(&internal_state.crc_handle, &current_data, 1);
    }

    if (crc_calculated == crc_host) {
        return CRC_RES_OK;
    }

    return CRC_RES_FAIL;
}

/**
 * @brief Verifies the address to be that of a flash or SRAM address.
 *
 * @param[in] data The address to be verified.
 * @return ADDR_RES_te ADDR_RES_OK, ADDR_RES_FAIL
 */
static ADDR_RES_te verify_addr(uint32_t addr, bool verify_t_bit) {
	if(verify_t_bit && (addr - 1) % 4 != 0) {
		return ADDR_RES_FAIL;
	}

	if(addr >= FLASH_BASE && addr <= FLASH_BANK1_END) {
		return ADDR_RES_OK;
	}
	else if(addr >= SRAM_BASE && addr <= SRAM_END) {
		return ADDR_RES_OK;
	}

	return ADDR_RES_FAIL;
}

/**
 * @brief Verifies the sectors to be erased.
 *
 * @param[in] start_sector The start_sector to be verified.
 * @param[in] num_sector The num_sector to be verified
 * @return SECT_RES_te SECT_RES_OK, SECT_RES_FAIL
 */
static SECT_RES_te verify_page(uint8_t start_page, uint8_t num_page) {
	// To perform mass erase
	if(start_page == 0xFF && num_page == 0) {
		return SECT_RES_OK;
	}

	if(
		start_page > PAGE_NUM - 1 ||
		(start_page + num_page > PAGE_NUM) ||
		num_page == 0
	) {
		return SECT_RES_FAIL;
	}

	return SECT_RES_OK;
}


/**
 * @brief Gets the version of the bootloader.
 *
 * @param[out] ver_o Pointer to the version buffer.
 * @param[in] buf_len Length of the version buffer.
 * @return 0 if success, -1 if failed.
 */
static int get_ver(char *ver_o, uint8_t buf_len) {
	uint8_t ver_len = strlen(CONFIG_BL_VERSION);
	if(ver_len > buf_len) {
		return -1;
	}

	strcpy(ver_o, CONFIG_BL_VERSION);

	return 0;
}

/**
 * @brief Gets the CRC of the given data.
 *
 * @param[in] data Pointer to the data buffer.
 * @param[in] data_len Length of the data buffer.
 * @return The calculated 32 bit CRC.
 */
static uint32_t get_crc(uint8_t *data, uint32_t data_len) {
	__HAL_CRC_DR_RESET(&internal_state.crc_handle);

	 uint32_t crc_calculated = 0;

	for(uint32_t i = 0; i < data_len; i++) {
        uint32_t current_data = data[i];
        crc_calculated = HAL_CRC_Accumulate(&internal_state.crc_handle, &current_data, 1);
	}

	return crc_calculated;
}
